[package]
authors = ["Godmode Galactus <gmgalactus@mango.markets>", "Maximilian Schneider <max@mango.markets>"]
edition = "2021"
name = "solana-bench-mango"
version = "1.10.26"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
borsh = "0.9.3"
chrono = "0.4.19"
clap = "2.33.1"
crossbeam-channel = "0.5"
fixed = { version = ">=1.11.0, <1.12.0", features = ["serde"] }
fixed-macro = "^1.1.1"
multiqueue = "^0.3.2"
log = "0.4.14"
rand = ">=0.8.5"
rayon = "1.5.1"
serde = "1.0.136"
serde_derive = "1.0.103"
serde_json = "1.0.79"
serde_yaml = "0.8.23"

mango = { git = "https://github.com/blockworks-foundation/mango-v3.git", branch = "mango_bencher_compatible", default-features = false, features = ["no-entrypoint"] }
mango-common = { git = "https://github.com/blockworks-foundation/mango-v3.git", branch = "mango_bencher_compatible" }

solana-client = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-core = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-metrics = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-rpc = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-runtime = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-sdk = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-clap-utils = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-cli-config = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-net-utils = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-version = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-logger = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }
solana-transaction-status = { git = "https://github.com/solana-labs/solana.git", branch="v1.14" }

thiserror = "1.0"
solana-program = ">=1.9.0"
csv = "1.0.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

exclude = [
    "deps/solana",
    "deps/mango-v3",
]